document.getElementById('generateButton').addEventListener('click', generateRizz);

const rizzQuotes = [
    "Is your dad an artist? Because you're a masterpiece.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Are you an electrician? Because you’re lighting up my life.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you have a name, or can I call you mine?",
    "Are you French? Because Eiffel for you.",
    "If you were a triangle, you’d be acute one.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "If you were a fruit, you'd be a fineapple.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Is there a sparkle in your eye, or are you just happy to see me?",
    "Are you an alien? Because you just abducted my heart.",
    "Can I follow you home? Because my parents always told me to follow my dreams.",
    "Is it hot in here or is it just you?",
    "Do you have a sunburn, or are you always this hot?",
    "Are you a time traveler? Because I can see you in my future.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Is your name Wi-Fi? Because I'm feeling a connection.",
    "Are you Australian? Because when I look at you, I feel like I'm down under.",
    "Are you a loan from a bank? Because you have my interest.",
    "Are you a beaver? Because daaaaam!",
    "If you were a vegetable, you’d be a cute-cumber.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Do you have a mirror in your pocket? Because I can see myself in your future.",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Are you a snowstorm? Because you just made my heart freeze.",
    "Are you a sea? Because I’m lost in your waves.",
    "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.",
    "Is your dad a scientist? Because you’re out of this world.",
    "Are you a star? Because your beauty lights up the night.",
    "Do you have a name, or can I call you mine?",
    "Are you an angel? Because you’ve fallen from heaven.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a magician? Because your beauty is making me spellbound.",
    "Is your name Bluetooth? Because I’m feeling a connection.",
    "Are you a cloud? Because you make my day brighter.",
    "Is your dad a chef? Because you’re making my heart melt.",
    "Are you a work of art? Because I’d like to hang you on my wall.",
    "Are you a beaver? Because daaaaam!",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Are you a snowflake? Because you’re one of a kind.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Is your name Wi-Fi? Because I'm feeling a connection.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "If you were a burger at McDonald's, you’d be the McGorgeous.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Are you a dictionary? Because you add meaning to my life.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a sunrise? Because you’re brightening up my day.",
    "Is your dad a scientist? Because you’re out of this world.",
    "Are you a snowflake? Because you’re one of a kind.",
    "Do you have a mirror in your pocket? Because I can see myself in your future.",
    "Are you an angel? Because you’ve fallen from heaven.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a beaver? Because daaaaam!",
    "Do you have a name, or can I call you mine?",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is your name Chapstick? Because you’re making my lips feel so good.",
    "Are you a dictionary? Because you add meaning to my life.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Do you have a name, or can I call you mine?",
    "Are you a magician? Because your beauty is making me spellbound.",
    "Is your name Bluetooth? Because I’m feeling a connection.",
    "Are you a cloud? Because you make my day brighter.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a snowflake? Because you’re one of a kind.",
    "If you were a vegetable, you'd be a cutecumber.",
    "Are you a beaver? Because daaaaam!",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Do you have a mirror in your pocket? Because I can see myself in your future.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a time traveler? Because I can see you in my future.",
    "Do you have a sunburn, or are you always this hot?",
    "Are you a loan from a bank? Because you have my interest.",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Is your dad an artist? Because you're a masterpiece.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Are you an electrician? Because you’re lighting up my life.",
    "If you were a vegetable, you'd be a cute-cumber.",
    "Do you have a name, or can I call you mine?",
    "Are you French? Because Eiffel for you.",
    "If you were a triangle, you’d be acute one.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "If you were a fruit, you'd be a fineapple.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Is there a sparkle in your eye, or are you just happy to see me?",
    "Are you an alien? Because you just abducted my heart.",
    "Can I follow you home? Because my parents always told me to follow my dreams.",
    "Is it hot in here or is it just you?",
    "Do you have a sunburn, or are you always this hot?",
    "Are you a time traveler? Because I can see you in my future.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Is your name Wi-Fi? Because I'm feeling a connection.",
    "Are you Australian? Because when I look at you, I feel like I'm down under.",
    "Are you a loan from a bank? Because you have my interest.",
    "Are you a beaver? Because daaaaam!",
    "If you were a vegetable, you’d be a cute-cumber.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Do you have a mirror in your pocket? Because I can see myself in your future.",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Are you a snowstorm? Because you just made my heart freeze.",
    "Are you a sea? Because I’m lost in your waves.",
    "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.",
    "Is your dad a scientist? Because you’re out of this world.",
    "Are you a star? Because your beauty lights up the night.",
    "Do you have a name, or can I call you mine?",
    "Are you an angel? Because you’ve fallen from heaven.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a magician? Because your beauty is making me spellbound.",
    "Is your name Bluetooth? Because I’m feeling a connection.",
    "Are you a cloud? Because you make my day brighter.",
    "Is your dad a chef? Because you’re making my heart melt.",
    "Are you a work of art? Because I’d like to hang you on my wall.",
    "Are you a beaver? Because daaaaam!",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Are you a snowflake? Because you’re one of a kind.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Is your name Wi-Fi? Because I'm feeling a connection.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "If you were a burger at McDonald's, you’d be the McGorgeous.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Are you a dictionary? Because you add meaning to my life.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a sunrise? Because you’re brightening up my day.",
    "Is your dad a scientist? Because you’re out of this world.",
    "Are you a snowflake? Because you’re one of a kind.",
    "Do you have a mirror in your pocket? Because I can see myself in your future.",
    "Are you an angel? Because you’ve fallen from heaven.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a beaver? Because daaaaam!",
    "Do you have a name, or can I call you mine?",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Do you have a pencil? Because I want to erase your past and write our future.",
    "Are you a time traveler? Because I can see you in my future.",
    "Is your name Chapstick? Because you’re making my lips feel so good.",
    "Are you a dictionary? Because you add meaning to my life.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a camera? Because every time I look at you, I smile.",
    "Do you have a name, or can I call you mine?",
    "Are you a magician? Because your beauty is making me spellbound.",
    "Is your name Bluetooth? Because I’m feeling a connection.",
    "Are you a cloud? Because you make my day brighter.",
    "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
    "Are you a snowflake? Because you’re one of a kind.",
    "If you were a vegetable, you'd be a cutecumber.",
    "Are you a beaver? Because daaaaam!",
    "Do you have a map? Because I keep getting lost in your eyes.",
    "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.",
    "Is your dad a baker? Because you’re a cutie pie.",
    "Are you a campfire? Because you bring warmth to my heart.",
    "Do you have a mirror in your pocket? Because I can see myself in your future.",
    "Are you a magician? Because whenever I look at you, everyone else disappears.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "If you were a fruit, you'd be a fineapple.",
    "Are you a time traveler? Because I can see you in my future.",
    "Do you have a sunburn, or are you always this hot?",
    "Are you a loan from a bank? Because you have my interest."
];
  
function generateRizz() {
    const randomIndex = Math.floor(Math.random() * rizzQuotes.length);
    document.getElementById('quote').innerText = rizzQuotes[randomIndex];
}
